I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2893, in script
    g "……………"
OSError: Couldn't find file 'Taz - たそがれ月.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2893, in script
    g "……………"
  File "/opt/apps/renpy/renpy/ast.py", line 2560, in execute
    Say.execute(self)
  File "/opt/apps/renpy/renpy/ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/opt/apps/renpy/renpy/exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "/opt/apps/renpy/renpy/character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/opt/apps/renpy/renpy/character.py", line 1045, in do_display
    display_say(who,
  File "/opt/apps/renpy/renpy/character.py", line 741, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/opt/apps/renpy/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/opt/apps/renpy/renpy/display/core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/opt/apps/renpy/renpy/display/core.py", line 3026, in interact_core
    renpy.audio.audio.periodic()
  File "/opt/apps/renpy/renpy/audio/audio.py", line 1199, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "/opt/apps/renpy/renpy/audio/audio.py", line 1177, in periodic_thread_main
    periodic_pass()
  File "/opt/apps/renpy/renpy/audio/audio.py", line 1119, in periodic_pass
    c.periodic()
  File "/opt/apps/renpy/renpy/audio/audio.py", line 528, in periodic
    topf = load(filename)
  File "/opt/apps/renpy/renpy/audio/audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "/opt/apps/renpy/renpy/loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'Taz - たそがれ月.mp3'.

Linux-6.9.11-x64v4-xanmod1-x86_64-with-glibc2.39 x86_64
Ren'Py 8.2.3.24061702
Khime_jamais_vu 1.0.2
Tue Jul 30 13:01:48 2024
